AbhsChinese.School/Models/CashVoucher/CahsVoucherDetailsSearch.cs
using AbhsChinese.Domain.Dto.Request;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AbhsChinese.School.Models.CashVoucher
{
    public class CahsVoucherDetailsSearch : DtoSearch
    {
        public int CashVoucherId { get; set; }

        public int Status { get; set; }

        public string UsedReferNo { get; set; }
    }
}

AbhsChinese.School/Models/CashVoucher/CashVoucherInputModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AbhsChinese.School.Models.CashVoucher
{
    public class CashVoucherInputModel
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int VoucherType { get; set; }

        public int PublishCount { get; set; }

        public decimal Amount { get; set; }

        public int LimitByPerson { get; set; }

        public int OrderAmountLimit { get; set; }

        public int ExpireType { get; set; }
        public DateTime ExpireDate { get; set; }
        public int ExpireDay { get; set; }

        public int SchoolType { get; set; }
        public int SchoolId { get; set; }

        public int ApplyScopeType { get; set; }
        public int Grade { get; set; }
        public int CourseType { get; set; }
        public int CourseId { get; set; }

        public string Remark { get; set; }

        //成单赠券
        public int RelatedCourseId { get; set; }

        /// <summary>
        /// 可叠加赠券（暂无）
        /// </summary>
        public int UseWithVoucherType { get; set; }
    }
}

AbhsChinese.School/Models/CashVoucher/CashVoucherSearch.cs
using AbhsChinese.Domain.Dto.Request;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AbhsChinese.School.Models.CashVoucher
{

    public class CashVoucherSearch : DtoSearch
    {
        public int SchoolId { get; set; }
        public int Id { get; set; }

        public string Name { get; set; }

        public int Status { get; set; }

        //public int CashType { get; set; }
    }
}

AbhsChinese.School/Controllers/CashVoucherController.cs
using AbhsChinese.Bll;
using AbhsChinese.Code.Common;
using AbhsChinese.Domain.Dto.Request;
using AbhsChinese.Domain.Dto.Response;
using AbhsChinese.Domain.Enum;
using AbhsChinese.School.Models.CashVoucher;
using AbhsChinese.School.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AbhsChinese.School.Controllers
{
    public class CashVoucherController : BaseController
    {
        // GET: CashVoucher
        public ActionResult Index()
        {
            CashVoucherSearch search = new CashVoucherSearch();
            search.SchoolId = CurrentUser.Teacher.Yoh_SchoolId;
            return View(search);
        }
        public ActionResult GetCashVoucheres(CashVoucherSearch search)
        {
            CashVoucherBll cashVoucherBll = new CashVoucherBll();
            var viewModels = cashVoucherBll.GetPagingCashVoucherForSchool(search.Pagination, search.Id, search.Name, search.Status, search.SchoolId);
            var table = AbhsTableFactory.Create(viewModels, search.Pagination.TotalCount);
            return Json(table, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <returns></returns>
        public ActionResult Edit(int id = 0)
        {
            if (id > 0)//禁止编辑
            {
                return RedirectToAction("Index");
            }
            CashVoucherBll cashVoucherBll = new CashVoucherBll();
            CourseBll bll = new CourseBll();
            DtoCashVoucher voucher = new DtoCashVoucher();
            decimal CashVoucherLimit = -1;
            if (id > 0)
            {
                voucher = cashVoucherBll.GetVoucherById(id);
                if (voucher != null)
                {
                    var priceModel = bll.GetCoursePrice(voucher.Ycv_CourseId, CurrentUser.School.Bsl_Level);
                    if (priceModel != null)
                    {
                        CashVoucherLimit = Math.Floor(priceModel.Yce_Price * (100 - CurrentUser.School.Bhl_DividePercent) / 100);
                    }
                }
            }
            ViewBag.CashVoucherLimit = CashVoucherLimit;
            ViewBag.DividePercent = CurrentUser.School.Bhl_DividePercent;
            return View(voucher);
        }

        [HttpPost]
        public ActionResult Save(CashVoucherInputModel inputModel)
        {
            inputModel.SchoolId = CurrentUser.Teacher.Yoh_SchoolId;
            inputModel.SchoolType = 1;
            inputModel.ExpireType = (int)ExpireTypeEnum.截止日期;
            inputModel.ApplyScopeType = (int)CashApplyScopeTypeEnum.指定课程;
            inputModel.VoucherType = (int)VoucherTypeEnum.校区券;
            CashVoucherBll cashVoucherBll = new CashVoucherBll();
            var request = inputModel.ConvertTo<DtoCashVoucherRequest>();
            request.Grade = 0;
            request.CourseType = 0;
            var success = false;
            if (inputModel.Id > 0)
            {
                success = cashVoucherBll.Update(request);
            }
            else
            {
                request.Creator = CurrentUser.Teacher.Yoh_Id;
                request.Editor = CurrentUser.Teacher.Yoh_Id;
                success = cashVoucherBll.Add(request) > 0;
            }
            return SimpleResult(success);
        }

        /// <summary>
        /// 查看—现金券明细
        /// </summary>
        /// <returns></returns>
        public ActionResult CashVoucherDetails(int cashVoucherId = 0)
        {
            if (cashVoucherId == 0)
            {
                return View();
            }
            CashVoucherBll cashVoucherBll = new CashVoucherBll();
            var viewModel = cashVoucherBll.GetCashVoucherDetail(cashVoucherId);
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult GetStudentCashVoucheres(CahsVoucherDetailsSearch search)
        {
            CashVoucherBll cashVoucherBll = new CashVoucherBll();
            var viewModels = cashVoucherBll.GetPagingStudentCashVoucher(search.Pagination, search.CashVoucherId, search.Status, search.UsedReferNo);
            var table = AbhsTableFactory.Create(viewModels, search.Pagination.TotalCount);
            return Json(table, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult UpdateStatus(int id, int status)
        {
            CashVoucherBll cashVoucherBll = new CashVoucherBll();
            var result = cashVoucherBll.UpdateStatus(id, status);
            return SimpleResult(result);
        }
    }
}

AbhsChinese.School/Controllers/Select2Controller.cs
using AbhsChinese.Bll;
using AbhsChinese.Code.Common;
using AbhsChinese.Domain.Entity;
using AbhsChinese.Domain.Enum;
using AbhsChinese.School.Controllers;
using AbhsChinese.School.Models.Common;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace AbhsChinese.Admin.Controllers
{
    public class Select2Controller : BaseController
    {

        RegionBll regionBll = new RegionBll();
        CourseBll courseBll = new CourseBll();
        SchoolBll schoolBll = new SchoolBll();
        SchoolClassBll schoolClassBll = new SchoolClassBll();
        SchoolTeacherBll schoolTeacherBll = new SchoolTeacherBll();

        [HttpGet]
        public ActionResult GetCourseTypes()
        {
            var options = CustomEnumHelper.GetElements(typeof(CourseCategoryEnum));
            var result = OptionFactory.CreateOptions(options);
            return Select2(result);
        }

        [HttpGet]
        public ActionResult GetCurriculumCategaries()
        {
            var categories = CustomEnumHelper.GetElements(typeof(CourseCategoryEnum));
            var result = OptionFactory.CreateOptions(categories);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetDifficulties()
        {
            var difficuties = CustomEnumHelper.GetElements(typeof(DifficultyEnum));
            var result = OptionFactory.CreateOptions(difficuties);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetEmployeeStatus()
        {
            var textType = CustomEnumHelper.GetElements(typeof(StatusEnum));
            var result = OptionFactory.CreateOptions(textType);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetGrades()
        {
            var difficuties = CustomEnumHelper.GetElements(typeof(GradeEnum));
            var result = OptionFactory.CreateOptions(difficuties);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetMediaType()
        {
            var mediaType = CustomEnumHelper.GetElements(typeof(MediaResourceTypeEnum));
            var result = OptionFactory.CreateOptions(mediaType);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetMediaTypeExceptXiaoAi()
        {
            var mediaType = CustomEnumHelper.GetElements(typeof(MediaResourceTypeEnum));
            mediaType.Remove((int)MediaResourceTypeEnum.小艾说);
            mediaType.Remove((int)MediaResourceTypeEnum.开场语);
            mediaType.Remove((int)MediaResourceTypeEnum.小艾变);
            var result = OptionFactory.CreateOptions(mediaType);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCourse(int type, int grade)
        {
            var dic = courseBll.GetCourseByTypeAndGrade(type, grade);
            return Json(dic, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult GetTeacherByGrade(int grade)
        {
            int schoolId = CurrentUser.Teacher.Yoh_SchoolId;
            var dic = schoolTeacherBll.GetTeacherByGrade(grade, schoolId);
            return Json(dic, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTextType()
        {
            var textType = CustomEnumHelper.GetElements(typeof(TextResourceTypeEnum));
            var result = OptionFactory.CreateOptions(textType);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult GetVoucherStatus()
        {
            var voucherStatus = CustomEnumHelper.GetElements(typeof(VoucherStatusEnum));
            var result = OptionFactory.CreateOptions(voucherStatus);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetStuentCashVoucherStatus()
        {
            var voucherStatus = CustomEnumHelper.GetElements(typeof(StudentCashVoucherStatusEnum));
            var result = OptionFactory.CreateOptions(voucherStatus);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetRegion(int parentId = 0)
        {
            var list = regionBll.GetRegionList(parentId).ToDictionary(k => { return k.Reg_ID; }, v => { return v.Reg_Name; });
            var result = OptionFactory.CreateOptions(list);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSchoolClassByCourseId(int courseId)
        {
            int schoolId = CurrentUser.Teacher.Yoh_SchoolId;
            var dic = schoolClassBll.GetSchoolClassByCourseId(courseId, schoolId).ToDictionary(k => { return k.Ycc_Id; }, v => { return v.Ycc_Name; });
            var result = OptionFactory.CreateOptions(dic);
            return Select2(result, JsonRequestBehavior.AllowGet);
        }
        protected JsonResult Select2(
            object data,
            JsonRequestBehavior behavior = JsonRequestBehavior.AllowGet)
        {
            return Json(new { results = data }, null, null, behavior);
        }
    }
}

AbhsChinese.School/Views/CashVoucher/CashVoucherDetails.cshtml
@using AbhsChinese.Code.Common
@using AbhsChinese.Domain.Enum
@using AbhsChinese.Domain.Dto.Response
@model DtoCashVoucher
@{
    ViewBag.Title = "CashVoucherDetails";
    ViewBag.HasBackBtn = true;
    ViewBag.PageTitle = "现金券明细";
}
@section Styles{
    @Styles.Render("~/bundles/css/abhsTableStyles")
    <style>
        .shorttd {
            background: #f9fafc;
        }

        .longtd {
            height: 50px;
            vertical-align: middle !important;
        }
        .cash-detail-content{
            height:100%;
        }
        /*abhsTable*/
        #table_voucher {
            height: calc(100% - 84px);
        }

        .table_container {
            height: 100%;
        }

        #page-wrapper {
            height: 100%;
        }

        #wrapper {
            height: 100%;
        }

        .wrapper {
            height: calc(100% - 198px);
        }
    </style>
}
<div class="cash-detail-content">
    <div class="ibox" style="margin-bottom:2px;">
        <div class="ibox-content" style="padding-bottom:0px;">
            <div class="row">
                <div class="col-12">
                    <table class="table table-bordered toptable text-center">
                        <tr>
                            <th class="shorttd">编号</th>
                            <th class="shorttd">名称</th>
                            <th class="shorttd">适用课程</th>
                            <th class="shorttd">使用门槛</th>
                            <th class="shorttd">面值</th>
                            <th class="shorttd">有效期</th>
                            <th class="shorttd">状态</th>
                        </tr>
                        <tr>
                            <td class="longtd">@(Model!=null?Model.Ycv_Id:0)</td>
                            <td class="longtd">@(Model != null ? Model.Ycv_Name : "")</td>
                            <td class="longtd">@(Model != null ? (Model.Ycv_CourseId == 0 ? "全部课程" : Model.Ycs_Name) : "")</td>
                            <td class="longtd">@(Model != null ? (Model.Ycv_OrderAmountLimit == 0 ? "无门槛" : "满￥" + Model.Ycv_OrderAmountLimit.ToString("0.00") + "元可用") : "")</td>
                            <td class="longtd">@(Model != null ? "￥" + Model.Ycv_Amount.ToString("0.00") : "")</td>
                            <td class="longtd">@(Model != null ? (Model.Ycv_ExpireType == 0 ? "长期有效" : Model.Ycv_ExpireType == 1 ? Model.ExpireDate : "领取" + Model.Ycv_ExpireDayCount + "天后有效") : "")</td>
                            <td class="longtd">@(Model != null ? ((Model.Ycv_PublishCount > Model.Ycv_TakenCount) ? "未领完" : "已领完") : "")</td>
                        </tr>
                        <tr>
                            <th class="shorttd">总发行量</th>
                            <th class="shorttd">已领取</th>
                            <th class="shorttd">待领取</th>
                            <th class="shorttd">已使用</th>
                            <th class="shorttd">未使用</th>
                            <th class="shorttd" colspan="2">备注</th>
                        </tr>
                        <tr>
                            <td class="longtd">@(Model != null ? Model.Ycv_PublishCount : 0)</td>
                            <td class="longtd">@(Model != null ? Model.Ycv_TakenCount : 0)</td>
                            <td class="longtd">@(Model != null ? (Model.Ycv_PublishCount-Model.Ycv_TakenCount) : 0)</td>
                            <td class="longtd">@(Model != null ? Model.UsedCount : 0)</td>
                            <td class="longtd">@(Model != null ? (Model.Ycv_TakenCount-Model.UsedCount) : 0)</td>
                            <td class="longtd" colspan="2">@(Model != null ? Model.Ycv_Remark:"")</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="ibox" style="height: calc(100% - 214px); margin-top:25px;">
        <div class="ibox-content" style="height: 100%;">
            <div class="row">
                <div class="col-12">
                    <form role="form" class="search-form" id="form_search_voucher">
                        <div class="form-group row">
                            <input type="hidden" value="@(Model!=null?Model.Ycv_Id:0)" name="CashVoucherId" />
                            <label class="col-1 col-form-label text-right">使用状态：</label>
                            <div class="col-2">
                                @*<input type="text" class="form-control" name="Status" />*@
                                <select class="select2 form-control" data-ajax--url="@Url.Action("GetStuentCashVoucherStatus","Select2")"
                                        data-ajax--cache="true"
                                        data-placeholder="全部"
                                        data-allow-clear="true"
                                        name="Status">
                                    <option></option>
                                </select>
                            </div>
                            <label class="col-1 col-form-label text-right">订单编号：</label>
                            <div class="col-2">
                                <input type="text" class="form-control" name="UsedReferNo" />
                            </div>
                        </div>
                        <div class="ibox-tools" style="top:1px;">
                            <div class="form-group">
                                <button class="btn btn-white search" type="button">
                                    &nbsp;&nbsp;搜索&nbsp;&nbsp;
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>


            <div class="row" style="height:calc(100% - 38px);">
                <div class="col-12 table_container">
                    <div id="table_voucher"></div>
                    <div class="pagination"></div>
                </div>
            </div>
        </div>
    </div>
</div>
    @section Scripts{
        @Scripts.Render("~/bundles/js/abhsTable")
        <script src="~/Scripts/common/date.js"></script>
        <script>
            $(function () {
                setMinHeight('cash-detail-content', 150);
                $('.select2.form-control').select2({
                    width: '100%',
                    allowClear: true,
                    minimumResultsForSearch: Infinity
                }).on('change', function (e) {
                    $(this).valid();
                });

                initTable();
            });

            function initTable() {
                let columns = [
                    { label: '券编号', name: 'Ysv_VoucherNo', align: 'center' },
                    { label: '领取用户', name: 'Bst_Phone', align: 'center' },
                    {
                        label: '领取方式', name: 'Ysv_GotType', align: 'center',
                        formatter: function (index, value, row) {
                            if (row.Ysv_GotType == 1) {
                                return "主动领取"
                            }
                            return "后台赠送";
                        }
                    },
                    { label: '领取时间', name: 'TakenTime', align: 'center' },
                    {
                        label: '当前状态', name: 'Ysv_Status', align: 'center',
                        formatter: function (index, value, row) {
                            if (row.Ysv_Status == 2) {
                                return "已使用"
                            }
                            if (row.Ysv_Status == 1) {
                                var start = row.ExpireDate;
                                var end = CurrentDate();
                                start = start.replace(/-/g, '/');
                                end = end.replace(/-/g, '/');
                                console.log(row.Ysv_ExpireDate)
                                var sTimes = new Date(Date.parse(start));
                                var eTimes = new Date(Date.parse(end));
                                console.log(sTimes);
                                console.log(eTimes);
                                if (sTimes.getTime() >= eTimes.getTime()) {
                                    return "未使用";
                                }
                                return "已过期";
                            }
                            return "";
                        }
                    },
                    {
                        label: '使用时间', name: 'UsedTime', align: 'center',
                        formatter: function (index, value, row) {
                            if (row.UsedTime == "1900-01-01 00:00:00") {
                                return "";
                            }
                            return "<span>" + row.UsedTime + "</span>";
                        }
                    },
                    {
                        label: '订单编号', name: 'Ysv_UsedReferNo', align: 'center',
                        formatter: function (index, value, row) {
                            if (row.Ysv_UsedReferNo == null) {
                                return "";
                            }
                            return "<span>" + row.Ysv_UsedReferNo + "</span>";
                        }
                    }
                ];

                $('#table_voucher').table({
                    ajax: {
                        url: '@Url.Action("GetStudentCashVoucheres", "CashVoucher")'
                    },
                    columns: columns,
                    searchBox: '#form_search_voucher'
                });
            }
        </script>
    }

AbhsChinese.School/Views/CashVoucher/_SearchCashVoucherList.cshtml
@model AbhsChinese.School.Models.CashVoucher.CashVoucherSearch
<form role="form" class="form-inline search-form col-10 col-md-9" id="form_search">
    <input type="hidden" name="SchoolId" value="@Model.SchoolId"  />
    <div class="form-group">
        <input type="text" class="form-control" name="Id" placeholder="按编号搜索" />
    </div>
    <div class="form-group">
        <input type="text" class="form-control" name="Name" placeholder="按名称搜索" />
    </div>
    <div class="form-group">
        <select class="form-control m-b select2 select2-cash-status" name="Status"></select>
    </div>
    <button class="btn btn-white search" type="button">
        搜索
    </button>
</form>