AbhsChinese.Admin/Controllers/CourseController.cs
using AbhsChinese.Admin.Models.Common;
using AbhsChinese.Admin.Models.Course;
using AbhsChinese.Bll;
using AbhsChinese.Code.Common;
using AbhsChinese.Code.Json;
using AbhsChinese.Domain.Dto.Request;
using AbhsChinese.Domain.Dto.Response;
using AbhsChinese.Domain.Entity;
using AbhsChinese.Domain.Enum;
using AbhsChinese.Domain.JsonTranslator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace AbhsChinese.Admin.Controllers
{
    
    /// <summary>
    /// 课程控制器
    /// </summary>
    public class CourseController : BaseController
    {
        [HttpGet]
        public ActionResult AddCourse()
        {
            return View();
        }


        [HttpPost, ActionName("AddCourse")]
        public ActionResult AddCourseConfirm(CourseInputModel input)
        {
            Domain.Dto.Request.DtoCourse course = input.ConvertTo<Domain.Dto.Request.DtoCourse>();
            course.CurrentUser = CurrentUserID;

            CourseBll bll = new CourseBll();
            bll.AddCourse(course);

            return Json(new SuccessJsonResponse(Url.Action(nameof(ListCurriculums))));
        }

        /// <summary>
        /// 课程详情
        /// </summary>
        /// <param name="curriculumID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(id);
        }

        [HttpGet]
        /// <returns></returns>
        public ActionResult GetCurriculums(DtoCurriculumSearch search)
        {
            CourseBll bll = new CourseBll();
            IList<DtoCourseListItem> entities = bll.GetCourses(search);

            PropertyNamePrefixAction action = PropertyNamePrefixAction.Remove;
            IEnumerable<CourseViewModel> list =
                entities.Select(s => s.ConvertTo<CourseViewModel>(action));
            return Table(list, search.Pagination.TotalCount);
        }

        [HttpGet]
        public ActionResult GetDetails(int id)
        {
            CourseBll bll = new CourseBll();
            var dtoDetails = bll.GetDetails(id);
            var vm = dtoDetails.ConvertTo<CurriculumDetailsViewModel>(
                PropertyNamePrefixAction.Remove);
            vm.CoverImage = UeditorContentFactory.RestoreUrl(
                vm.CoverImage, UeditorType.Image);
            SuccessJsonResponse response = new SuccessJsonResponse { Data = vm };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 获取课程下的课时
        /// </summary>
        /// <param name="id">课程的id</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetLessons(int courseId)
        {
            LessonBll bll = new LessonBll();
            var lessons = bll.GetLessons(courseId);
            var result = lessons.ConvertTo<IList<LessonViewModel>>();
            SuccessJsonResponse response = new SuccessJsonResponse { Data = result };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CloseCourse(int courseId)
        {
            CourseBll bll = new CourseBll();
            var course = bll.GetCourse(courseId);
            if (course.Ycs_Status == (int)CourseStatusEnum.已上架)
            {
                return Json(new JsonSimpleResponse
                {
                    State = false,
                    ErrorMsg = "已上架的课程不能关闭"
                });
            }
            bll.UpdateStatus(
                    courseId,
                    CourseStatusEnum.已关闭,
                    CourseActionEnum.关闭,
                    CurrentUserID);
            return Json(new SuccessJsonResponse());
        }

        [HttpPost]
        public ActionResult DeleteCourse(int courseId)
        {
            CourseBll bll = new CourseBll();
            var course = bll.GetCourse(courseId);
            if (course.Ycs_Status != (int)CourseStatusEnum.已关闭)
            {
                return Json(new JsonSimpleResponse
                {
                    State = false,
                    ErrorMsg = "只有已关闭的课程才能删除"
                });
            }
            bll.UpdateStatus(
                    courseId,
                    CourseStatusEnum.已删除,
                    CourseActionEnum.删除,
                    CurrentUserID);
            return Json(new SuccessJsonResponse());
        }

        [HttpPost]
        public ActionResult ReopenCourse(int courseId)
        {
            CourseBll bll = new CourseBll();
            bll.ReopenCourse(courseId, CurrentUserID);
            return Json(new SuccessJsonResponse());
        }

        /// <summary>
        /// 获取操作日志
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetLogs(int courseId)
        {
            CourseBll bll = new CourseBll();
            var lessons = bll.GetLogs(courseId);
            var result = lessons.ConvertTo<IList<LessonViewModel>>();
            SuccessJsonResponse response = new SuccessJsonResponse { Data = result };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 课程管理视图
        /// </summary>
        /// <returns></returns>
        public ActionResult ListCurriculums()
        {
            return View();
        }

        private JsonResult Table<T>(IEnumerable<T> data, int totalRecord)
            where T : class, new()
        {
            var result = AbhsTableFactory.Create(data, totalRecord);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

AbhsChinese.Admin/Controllers/CurriculumController.cs
using Abhs.Service.Client;
using AbhsChinese.Admin.Models.Common;
using AbhsChinese.Admin.Models.Course;
using AbhsChinese.Admin.Models.CurriculumSetViewModel;
using AbhsChinese.Bll;
using AbhsChinese.Code.Common;
using AbhsChinese.Code.Json;
using AbhsChinese.Domain.Dto.Request;
using AbhsChinese.Domain.Dto.Response;
using AbhsChinese.Domain.Entity;
using AbhsChinese.Domain.Enum;
using AbhsChinese.Domain.JsonTranslator;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web.Mvc;

namespace AbhsChinese.Admin.Controllers
{
    /// <summary>
    /// 课程控制器
    /// </summary>
    public class CurriculumController : BaseController
    {
        #region 管理
        /// <summary>
        /// 课程管理视图
        /// </summary>
        /// <returns></returns>
        public ActionResult Manage()
        {
            return View();
        }

        /// <summary>
        /// 课程详情
        /// </summary>
        /// <param name="curriculumID"></param>
        /// <returns></returns>
        public ActionResult Info(string curriculumID)
        {
            return View();
        }

        #endregion

        #region 审批

        /// <summary>
        /// 课时审批列表
        /// </summary>
        /// <returns></returns>
        public ActionResult Approve()
        {
            return View();
        }

        /// <summary>
        /// 课程审批
        /// </summary>
        /// <param name="curriculumID">课时id</param>
        /// <returns></returns>
        public ActionResult ChapterApprove(int id = 0)
        {
            LessonBll bll = new LessonBll();
            var data = bll.Select(id);
            if (data != null && data.Status == (int)LessonStatusEnum.待审批)
            {
                bll.UpdateLessonStatus(data.ID, LessonStatusEnum.审批中, base.CurrentUserID);
            }
            return View(id);
        }

        #endregion

        #region 制作
        /// <summary>
        /// 课程制作列表
        /// </summary>
        /// <returns></returns>
        public ActionResult Make()
        {
            return View();
        }
        /// <summary>
        /// 课程制作详情视图动作
        /// </summary>
        /// <returns></returns>
        public ActionResult MakeInfo(int id = 0)
        {
            CourseBll bll = new CourseBll();
            var model = bll.GetDetails(id);

            var vm = model.ConvertTo<CurriculumDetailsViewModel>(
                PropertyNamePrefixAction.Remove);
            vm.CoverImage = UeditorContentFactory.RestoreUrl(
                vm.CoverImage, UeditorType.Image);
            if (model != null)
            {
                return View(vm);
            }
            else
            {
                return View(new CurriculumDetailsViewModel());
            }
        }
        /// <summary>
        /// 制作课时视图
        /// </summary>
        /// <param name="chapterID">课时id</param>
        /// <returns></returns>
        public ActionResult MakeChapter(int id = 0)
        {
            LessonBll bll = new LessonBll();
            var data = bll.Select(id);
            if (data != null && data.Status == (int)LessonStatusEnum.未编辑)
            {
                bll.UpdateLessonStatus(data.ID, LessonStatusEnum.制作中, base.CurrentUserID);
            }
            return View(id);
        }
        #endregion

        #region 课程课时相关查询接口
        /// <summary>
        /// 查询课程数据
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetCurriculums(DtoCurriculumSearch search)
        {
            CourseBll bll = new CourseBll();
            IList<DtoCourseListItem> entities = bll.GetCourses(search);

            PropertyNamePrefixAction action = PropertyNamePrefixAction.Remove;
            IEnumerable<CourseViewModel> list =
                entities.Select(s => s.ConvertTo<CourseViewModel>(action));
            return Json(AbhsTableFactory.Create(list, search.Pagination.TotalCount));
        }
        /// <summary>
        /// 查询审批课时数据
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetApproveLessons(DtoApproveLessonSearch search)
        {
            LessonBll bll = new LessonBll();
            List<DtoLessonApprove> list = bll.GetLessonApproveByPage(search);
            return Json(AbhsTableFactory.Create(list, search.Pagination.TotalCount));
        }
        /// <summary>
        /// 查询课程课时日志
        /// </summary>
        /// <param name="courseid"></param>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetLessonLog(int courseid, DtoSearch search)
        {
            LessonBll bll = new LessonBll();
            var list = bll.GetLessonLogByPage(courseid, search);
            return Json(AbhsTableFactory.Create(list, search.Pagination.TotalCount));

        }
        #endregion

        #region 审批&制作视图需要接口
        /// <summary>
        /// 根据课时id获取数据
        /// </summary>
        /// <param name="chapterid"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetChapter(int chapterid)
        {
            LessonBll lbll = new LessonBll();

            var lesson = lbll.Select(chapterid);
            if (lesson != null)
            {
                LessonUnitBll bll = new LessonUnitBll();
                ChapterSet set = new ChapterSet();
                set.courseId = lesson.CourseId;
                set.id = lesson.ID;
                set.name = lesson.Name;
                set.setTime = lesson.UpdateTime.ToString("yyyy-MM-dd HH:mm:ss");
                set.pages = new List<Page>();
                set.status = lesson.Status;
                set.processid = lesson.ProcessId;
                var units = bll.SelectUnitsByLesson(set.id, set.processid);
                if (units != null)
                {
                    set.pages = units.Select(u => new Page
                    {
                        courseId = u.CourseId,
                        lessonId = u.LessonId,
                        id = u.Id,
                        name = u.Name,
                        pageNum = u.Index,
                        thumbnail = string.IsNullOrEmpty(u.Screenshot) ? "" : (ConfigurationManager.AppSettings["OssHostUrl"] + u.Screenshot),
                        approveType = u.ApproveStatus
                    }).ToList();
                }
                return Json(new JsonResponse<ChapterSet> { State = true, ErrorCode = 0, ErrorMsg = "", Data = set });
            }
            else
            {
                return Json(new JsonResponse<ChapterSet> { State = false, ErrorCode = 0, ErrorMsg = "没有此数据", Data = null });
            }
        }
        /// <summary>
        /// 获取讲义数据
        /// </summary>
        /// <param name="pageid">审批id</param>
        /// <param name="processid">审批编号</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetPage(int pageid, int processid)
        {
            LessonUnitBll bll = new LessonUnitBll();
            var unit = bll.SelectUnit(pageid, processid);
            var page = new Page();
            page.courseId = unit.CourseId;
            page.lessonId = unit.LessonId;
            page.id = unit.Id;
            page.name = unit.Name;
            page.pageNum = unit.Index;
            ////定义媒体资源id数组和文本资源id数组
            List<int> mediaids = new List<int>(), textids = new List<int>();
            page.steps = unit.Steps.Select(s => new Models.CurriculumSetViewModel.Step
            {
                id = s.id,
                stepNum = s.StepNum,
                actions = s.Actions.Select(a => ActionTranslator.DataToViewData(a, mediaids, textids)).ToList()
            }).ToList();
            //如果媒体id或文本id有值的话
            if (mediaids.Count > 0 || textids.Count > 0)
            {
                ResourceBll rbll = new ResourceBll();
                var medias = rbll.GetMediaObjectByIdList(mediaids.Distinct().ToList());//获取所有的媒体对象字典
                var texts = rbll.GetTextObjectByIdList(textids.Distinct().ToList());//获取文本对象字典
                page.steps.ForEach((s) =>
                {
                    s.actions.ForEach((a) =>
                    {
                        ActionTranslator.SetViewDataMedia(a, medias, texts);//设置动作的媒体属性
                    });//遍历每一个动作
                });//遍历每一个步骤
            }
            page.approveType = unit.ApproveStatus;
            page.approve = unit.Approve;
            return Json(new JsonResponse<Page> { State = true, ErrorCode = 0, ErrorMsg = "", Data = page });
        }
        /// <summary>
        /// 添加讲义页
        /// </summary>
        /// <param name="page"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult AddPage(Page page)
        {
            LessonUnitBll bll = new LessonUnitBll();
            //修改数据
            int id = bll.Add(new DtoLessonUnit
            {
                CourseId = page.courseId,
                LessonId = page.lessonId,
                Name = "",
                Screenshot = "",
                Steps = null,
                Index = page.pageNum,
            });
            return Json(new JsonResponse<int> { State = true, ErrorCode = 0, ErrorMsg = "", Data = id });
        }
        /// <summary>
        /// 设置讲义数据
        /// </summary>
        /// <param name="pagestr"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]//不做html验证
        public JsonResult SetPage(string pagestr)
        {
            LessonUnitBll bll = new LessonUnitBll();
            Page pageInfo = new Page();
            #region 解析数据
            JObject obj = JsonConvert.DeserializeObject(pagestr) as JObject;

AbhsChinese.Admin/Views/Curriculum/Approve.cshtml
@{
    ViewBag.PageTitle = "课程审批";
}
<div class="ibox">
    <div class="ibox-content">
        <div class="row">
            <div class="col-12">
                <form role="form" class="form-inline search-form" id="form_search">
                    <input type="hidden" name="type" value="" />
                    <div class="form-group">
                        <input type="text" name="LessonNumber" placeholder="按编号搜索" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="text" name="LessonOrProducerName" placeholder="按课时名称，制作人员搜索" class="form-control">
                    </div>
                    <div class="form-group">
                        <select class="select2 normal" data-ajax--url="@Url.Action("GetCurriculumCategaries","Select2")"
                                data-ajax--cache="true"
                                data-placeholder="请选择类型" data-allow-clear="true"
                                name="CourseType"></select>
                    </div>
                    <div class="form-group">
                        <select class="select2 normal" data-ajax--url="@Url.Action("GetGrades","Select2")"
                                data-ajax--cache="true"
                                data-placeholder="请选择年级" data-allow-clear="true"
                                name="Grade"></select>
                    </div>
                    <button id="Seach" class="btn btn-white search" type="button">搜索</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12 table_container">
                <div id="table_list"></div>
                <div class="pagination"></div>
            </div>
        </div>
    </div>
</div>


@section Styles{
    @Styles.Render("~/bundles/css/abhsTableStyles")
    <style>
        #form_search {
            margin: 0px;
        }

            #form_search .form-group {
                max-width: 20%;
            }

                #form_search .form-group .form-control {
                    width: 100%;
                }
    </style>

}

@section Scripts{
    @Scripts.Render("~/bundles/js/abhsTable")
    <script>
        $(function () {
            $('.select2.normal').select2({
                width: '197px',
                allowClear: true,
                minimumResultsForSearch: Infinity
            }).on('change', function (e) {
                $(this).valid();
            });



            window.lessonTable = $('#table_list').table({
                ajax: {
                    url: '@Url.Action("GetApproveLessons", "Curriculum")',
                    type: "post"
                },
                columns: [
                { label: '时间', name: 'UpdateDateStr', align: "center" },
                {
                    label: '课时编号', name: 'CourseID', align: "center",
                    formatter: function (index, value, row) {
                        return value + "-" + row.LessonIndex;
                    }
                },
                { label: '课时名称', name: 'LessonName', align: "center" },
                { label: '对应课程', name: 'CourseName', align: "center" },
                {
                    label: '第几课时', name: 'LessonIndex', align: "center",
                    formatter: function (index, value, row) {
                        return "第" + value + "课时";
                    }
                },
                { label: '课程类型', name: 'CourseTypeStr', align: "center" },
                { label: '年级', name: 'GradeStr', align: "center" },
                { label: '制作人员', name: 'LessonProducerName', align: "center" },
                { label: '课时状态', name: 'LessonStatusStr', align: "center" },
                {
                    label: '操作', name: 'LessonID', align: "center",
                    formatter: function (index, value, row) {
                        return '<a target="_blank" href="/Curriculum/ChapterApprove/' + value + '">操作</a>';
                    }
                }
                ],
                searchBox: '#form_search'
            });

        })
    </script>
}

AbhsChinese.Admin/Views/Curriculum/ChapterApprove.cshtml
@model int
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChapterApprove</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/CurriculumSet/animate.css" rel="stylesheet" />
    <link href="~/CurriculumSet/CurriculumSet.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/extend.js"></script>
    <script src="~/CurriculumSet/CurriculumClass.js"></script>
    <script src="~/CurriculumSet/CurriculumApprove.js"></script>
    <script>

        if (opener && opener.lessonTable) {
            opener.lessonTable.reload();
        }
        $(function () {

            $(".ShowList").click(function () {
                var child = $(this).children().first();
                if (child.hasClass("glyphicon-chevron-down")) {
                    child.removeClass("glyphicon-chevron-down").addClass("glyphicon-chevron-up");
                    $(".PageInnerBox").show();
                }
                else {
                    child.removeClass("glyphicon-chevron-up").addClass("glyphicon-chevron-down");
                    $(".PageInnerBox").hide();
                }
            });
            //请求界面数据
            $.ajax({
                url: "@Url.Action("GetChapter", "Curriculum")",
                type: "post",
                data: { chapterid: @Model },
                dataType: "json",
                async: false,
                success: Load,
                error: function (e) {
                    console.error("错了");
                }
            })
        })
    </script>
</head>
<body>
    <div class="TopBox">
        <h4 class="CurriculumTitle">课程题目</h4>
        <button id="NotOKBtn" class="ApproveBtn btn btn-danger">课时不合格</button>
        <button id="IsOkBtn" class="ApproveBtn btn btn-info">课时合格</button>
        <div class="PageBox">
            <div class="PageInnerBox">
                <div id="Pages">
                </div>
            </div>
            <div class="ShowList"><i class="glyphicon glyphicon-chevron-up"></i></div>
        </div>
    </div>
    <div class="InfoBox">
        <div id="ShowBox" class="ShowBox">
            @*<div id="ShowInfoBox" class="ShowInfo"></div>*@
            <iframe id="ShowInfoBox" class="ApproveShow"></iframe>
        </div>
        <div class="SetBox">
            <div id="ApproveBox">
                <ul class="ApproveTypes">
                    <li><label style="color:#000000;"><input type="radio" name="ApproveType" value="1" />本页正常</label></li>
                    <li><label style="color:#ff0000;"><input type="radio" name="ApproveType" value="2" />本页有错误</label></li>
                    <li><label style="color:#ff6a00;"><input type="radio" name="ApproveType" value="3" />本页有疑问</label></li>
                </ul>
                <div class="ApproveInfo">
                    <textarea id="ApproveText" class="ApproveText" placeholder="请输入本页审核意见"></textarea><br />
                    <div class="btn-toolbar">
                        @*<div id="PlayBtns" class="PlayBtns btn-group  btn-group-sm" role="group" aria-label="...">
                                <button id="lastBtn" type="button" class="btn btn-warning" title="上一步"><i class="glyphicon glyphicon-step-backward"></i></button>
                                <button id="playBtn" type="button" class="btn btn-warning" title="播放"><i class="glyphicon glyphicon-play"></i></button>
                                <button id="nextBtn" type="button" class="btn btn-warning" title="下一步"><i class="glyphicon glyphicon-step-forward"></i></button>

                            </div>*@
                        <div class="PlayBtns btn-group  btn-group-sm" role="group" aria-label="...">
                            <button id="SaveBtn" class="btn btn-info ApproveBtn">保存意见</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="LoadingBox"></div>
    <p id="LoadingText">数据加载中请稍后...</p>
</body>
</html>

AbhsChinese.Admin/Views/Curriculum/MakeInfo.cshtml
@model AbhsChinese.Admin.Models.Course.CurriculumDetailsViewModel

@{
    ViewBag.PageTitle = "课程制作-课程详情";
}

<div class="ibox">
    <div class="ibox-content">
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered table-sm details-container">
                    <tr>
                        <td rowspan="6" style="width:525px;text-align:center;">
                            <img src="@(string.IsNullOrWhiteSpace(Model.CoverImage)?"/Images/picture.jpg":Model.CoverImage)" class="img-fluid" alt="封面">
                        </td>
                        <th style="min-width:85px;">课程编号</th>
                        <td>@Model.Id</td>
                        <th style="min-width:85px;">课程名称</th>
                        <td>@Model.Name</td>
                    </tr>
                    <tr>
                        <th>课程类型</th>
                        <td>@Model.CourseTypeText</td>
                        <th>年级</th>
                        <td>@Model.GradeText</td>
                    </tr>
                    <tr>
                        <th>课时数量</th>
                        <td>@Model.LessonCount</td>
                        <th>负责人</th>
                        <td>@Model.OwnerName</td>
                    </tr>
                    <tr>
                        <th>参与老师</th>
                        <td colspan="3">@Model.Teachers</td>
                    </tr>
                    <tr>
                        <th>课程简介</th>
                        <td colspan="3">@Model.Description</td>
                    </tr>
                    <tr>
                        <th>资源组</th>
                        <td>@Model.ResourceGroupName</td>
                        <th>课程状态</th>
                        <td>@Model.StatusText</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li>
                            <a class="nav-link" data-toggle="tab" href="#tab-1">课时列表</a>
                            <input type="hidden" value="list" />
                        </li>
                        <li>
                            <a class="nav-link" data-toggle="tab" href="#tab-2">操作日志</a>
                            <input type="hidden" value="logs" />
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane">
                            <div class="panel-body table_container">
                                <form role="form" id="form_search_list">
                                    <input type="hidden" name="courseId" value="@Model.Id" />
                                    <button hidden class="search" type="button">搜索</button>
                                </form>
                                <div id="table_list"></div>
                                <div class="pagination"></div>
                            </div>
                        </div>
                        <div id="tab-2" class="tab-pane">
                            <div class="panel-body table_container">
                                <form role="form" id="form_search_logs">
                                    <input type="hidden" name="courseId" value="@Model.Id" />
                                    <button hidden class="search" type="button">搜索</button>
                                </form>
                                <div id="table_logs"></div>
                                <div class="pagination"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    @Styles.Render("~/bundles/css/abhsTableStyles")
    <style>
        .table > tbody > tr > th, .table > tbody > tr > td {
            vertical-align: middle;
        }
    </style>
}
@section Scripts{
    @Scripts.Render("~/bundles/js/abhsTable")
    <script src="~/Scripts/PageScripts/details.js"></script>
    <script>
        $(function () {
            initTabs();
            $('a[href="#tab-1"]').tab('show');
        });
        function initTabs() {
            $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                let tab = $(e.target).next().val();
                if (tab === 'list') {
                    initLessonTable();
                } else if (tab === 'logs') {
                    initLogTable();
                }
            })
        }
        function initLessonTable() {
            let align = 'center';
            let columns = [
                {
                    label: '编号', name: 'Index', align: align, formatter: function (i, value, row) {
                        return row.CourseId + "-" + value;
                    }
                },
                { label: '课时名称', name: 'Name', align: align },
                { label: '最后编辑时间', name: 'UpdateTimeText', align: align },
                { label: '制作人员', name: 'ProducerName', align: align },
                { label: '审批人员', name: 'ApproverName', align: align },
                { label: '课时状态', name: 'StatusText', align: align },
                {
                    label: '操作', name: "", align: "center", formatter: function (i, value, row) {
                        return "<a target='_blank' href='/Curriculum/MakeChapter/" + row.ID + "' >编辑</a>"
                    }
                }
            ];
            window.lessonTable = $('#table_list').table({

                ajax: {
                    url: '@Url.Action("GetLessons", "Course")'
                },
                columns: columns,
                searchBox: '#form_search_list'
            });
        }

        function initLogTable() {
            let align = 'center';
            let columns = [
                { label: '操作日期', name: 'CreateTimeStr', align: align },
                { label: '操作人', name: 'OperatorName', align: align },
                { label: '操作类型', name: 'StatusStr', align: align },
                { label: '操作记录', name: 'Remark', align: "left" }
            ];
            $('#table_logs').table({
                ajax: {
                    url: '@Url.Action("GetLessonLog", "Curriculum")',
                    type: "post",
                },
                columns: columns,
                searchBox: '#form_search_logs'
            });
        }
    </script>
}