AbhsChinese.Admin/Controllers/CourseManageController.cs
using AbhsChinese.Admin.Models.Common;
using AbhsChinese.Admin.Models.Course;
using AbhsChinese.Bll;
using AbhsChinese.Code.Common;
using AbhsChinese.Code.Json;
using AbhsChinese.Domain.Dto.Request;
using AbhsChinese.Domain.Dto.Response;
using AbhsChinese.Domain.Enum;
using AbhsChinese.Domain.JsonTranslator;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace AbhsChinese.Admin.Controllers
{
    public class CoverImageInputModel
    {
        public int CourseId { get; set; }
        public string CoverImage { get; set; }
    }
    public class CourseManageController : BaseController
    {
        [HttpGet]
        public ActionResult GetCourses(DtoCurriculumSearch search)
        {
            CourseBll bll = new CourseBll();
            IList<DtoCourseListItem> entities = bll.GetManageCourses(search);

            PropertyNamePrefixAction action = PropertyNamePrefixAction.Remove;
            IEnumerable<CourseViewModel> list =
                entities.Select(s => s.ConvertTo<CourseViewModel>(action));

            return Table(list, search.Pagination.TotalCount);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Pricing(CoursePricingInputModel input)
        {
            CourseBll bll = new CourseBll();
            input.CoverIamge = UeditorContentFactory.FetchUrl(
                input.CoverIamge, UeditorType.Image);
            DtoCoursePricing price = input.ConvertTo<DtoCoursePricing>();
            bll.Pricing(price, CurrentUserID);
            return Json(new SuccessJsonResponse());
        }

        public ActionResult ListCourses()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StopTrading(int courseId)
        {
            CourseBll bll = new CourseBll();
            var course = bll.GetCourse(courseId);
            if (course.Ycs_Status == (int)CourseStatusEnum.已上架)
            {
                bll.UpdateStatus(
                    courseId,
                    CourseStatusEnum.已下架,
                    CourseActionEnum.下架,
                    CurrentUserID);
                return Json(new SuccessJsonResponse());
            }
            else
            {
                return Json(new JsonSimpleResponse
                {
                    State = false,
                    ErrorMsg = "只有已上架的课程才能下架"
                });
            }
        }

        [HttpGet]
        public ActionResult Preview(int courseId)
        {
            string t = DateTime.Now.Ticks.ToString();
            string sign = Encrypt.MD5Hash(t, "8j0pf");
            string url = ConfigurationManager.AppSettings["StudentClientDomain"];
            string fullUrl = url + "Login/StudentLogin";
            return Json(new SuccessJsonResponse(new
            {
                Parameters = new
                {
                    T = t,
                    Sign = sign,
                    CourseId = courseId,
                },
                PreviewUrl = fullUrl
            }), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 上架
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult StartTrading(int courseId)
        {
            CourseBll bll = new CourseBll();
            var course = bll.GetCourse(courseId);
            if (course.Ycs_Status == (int)CourseStatusEnum.待上架)
            {
                bll.UpdateStatus(
                    courseId,
                    CourseStatusEnum.已上架,
                     CourseActionEnum.上架,
                    CurrentUserID);
                return Json(new SuccessJsonResponse());
            }
            else
            {
                return Json(new JsonSimpleResponse
                {
                    State = false,
                    ErrorMsg = "只有待上架的课程才能上架"
                });
            }
        }

        [HttpPost]
        public ActionResult AddCoverImage(CoverImageInputModel input)
        {
            CourseBll bll = new CourseBll();
            string imgUrl = UeditorContentFactory.FetchUrl(
                input.CoverImage, UeditorType.Image);
            bll.AddCoverImage(input.CourseId, imgUrl);
            return Json(new SuccessJsonResponse());
        }

        [HttpGet]
        public ActionResult RemoveCoverImage(CoverImageInputModel input)
        {
            CourseBll bll = new CourseBll();
            bll.RemoveCoverImage(input.CourseId);
            return Json(new SuccessJsonResponse(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetDetails(int id)
        {
            CourseBll bll = new CourseBll();
            var dtoDetails = bll.GetDetailOfManagements(id);
            var vm = dtoDetails.ConvertTo<CurriculumDetailsViewModel>(
                PropertyNamePrefixAction.Remove);
            vm.CoverImage = UeditorContentFactory.RestoreUrl(vm.CoverImage, UeditorType.Image);
            SuccessJsonResponse response = new SuccessJsonResponse { Data = vm };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        private JsonResult Table<T>(IEnumerable<T> data, int totalRecord)
            where T : class, new()
        {
            var result = AbhsTableFactory.Create(data, totalRecord);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 课程定价详情
        /// </summary>
        /// <param name="curriculumID"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(id);
        }
    }
}

AbhsChinese.Admin/Views/CourseManage/Details.cshtml
@model int?

@{
    ViewBag.PageTitle = "课程详情-已上架";
}

<div class="ibox">
    <div class="ibox-title">
        <div class="ibox-tools">
            <a href="@Url.Action("ListCourses", "CourseManage")"
               class="btn btn-default btn-sm"><i class="fa fa-chevron-left"></i>&nbsp;返回</a>
        </div>
    </div>
    <div class="ibox-content">
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered table-sm details-container" style="table-layout:fixed">
                    <tr>
                        <th style="width:527px;height:359px;padding:0px;" rowspan="6">
                            <div id="preview"></div>
                            <div id="dropz" class="dropzone"></div>
                        </th>
                        <th style="width:8%;">课程编号</th>
                        <td style="width:8%;">@Model</td>
                        <th style="width:8%;">课程名称</th>
                        <td name="Name"></td>
                    </tr>
                    <tr>
                        <th>年级</th>
                        <td name="GradeText"></td>
                        <th>课程类型</th>
                        <td><div class="short-text" name="CourseTypeText"></div></td>
                    </tr>
                    <tr>
                        <th>课时数量</th>
                        <td name="LessonCount"></td>
                        <th>负责人</th>
                        <td name="OwnerName"></td>
                    </tr>
                    <tr>
                        <th>已合格课时</th>
                        <td colspan="3">
                            <div class="short-text" name="ApprovedLessons"></div>
                        </td>
                    </tr>
                    <tr>
                        <th>课程简介</th>
                        <td colspan="3">
                            <div class="short-text" name="Description"></div>
                        </td>
                    </tr>
                    <tr>
                        <th>状态</th>
                        <td name="StatusText"></td>
                        <th>操作</th>
                        <td>
                            <button type="button" disabled onclick="startTrading(@Model)"
                                    id="btnStartTrading"
                                    class="btn btn-primary">
                                上架
                            </button>
                            <button type="button" disabled onclick="stopTrading(@Model)"
                                    id="btnStopTrading"
                                    class="btn btn-primary">
                                下架
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li>
                            <a class="nav-link" data-toggle="tab" href="#tab-1">课程设置</a>
                            <input type="hidden" value="list" />
                        </li>
                        <li>
                            <a class="nav-link" data-toggle="tab" href="#tab-2">操作日志</a>
                            <input type="hidden" value="logs" />
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab-1" class="tab-pane">
                            <div class="panel-body">
                                <form id="frm_pricing" action="@Url.Action("Pricing","CourseManage")" method="post">
                                    <input type="hidden" id="courseId" name="courseId" value="@Model" />
                                    <input type="hidden" name="nextStatus" value="2" />
                                    <input type="hidden" id="coverIamge" name="coverIamge" value="" />
                                    <div id="div_schoolLevelsContainer"></div>
                                    @*<div class="form-group row">
                                            <label class="col-sm-2 text-right col-form-label">课程排序</label>
                                            <div class="col-sm-9">
                                                <input type="number" min="0" required class="form-control" name="sort" value="" />
                                            </div>
                                        </div>*@
                                    <div class="form-group row">
                                        <label class="col-sm-2 text-right col-form-label">课程详情</label>
                                        <div class="col-sm-9">
                                            <textarea id="introduction" name="introduction"></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-2 text-right col-form-label">课程安排</label>
                                        <div class="col-sm-9">
                                            <textarea id="arrange" name="arrange"></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-12 text-center">
                                            <button type="button" class="btn btn-default" onclick="preview(@Model)">预览</button>
                                            <button type="button" id="btnOk" class="btn btn-primary"
                                                    style="display:none;"
                                                    onclick="savePrice(this)">
                                                确定
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div id="tab-2" class="tab-pane">
                            <div class="panel-body table_container">
                                <form role="form" id="form_search_logs">
                                    <input type="hidden" id="courseId" name="courseId" value="@Model" />
                                    <button hidden class="search" type="button">搜索</button>
                                </form>
                                <div id="table_logs"></div>
                                <div class="pagination"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="div_template_schoolLevel" style="display:none">
    <div class="form-group row">
        <label class="col-sm-2 text-right col-form-label required">$levelName：</label>
        <div class="col-sm-9">
            <div class="input-group m-b">
                <input type="number" min="0" step="0.1" required name="pricings[$index].price" class="form-control">
                <input type="hidden" name="pricings[$index].schoolLevelId" value="$value" class="form-control">
                <div class="input-group-append">
                    <span class="input-group-addon">￥</span>
                </div>
            </div>
            <label for="pricings[$index].price" class="error" style="display:none;"></label>
        </div>
    </div>
</div>

<input type="hidden" id="urlToGetPreviewParameters"
       value="@Url.Action("Preview","CourseManage")" />

@section Styles{
    @Styles.Render("~/bundles/css/abhsTableStyles")
    <link href="~/Content/dropzone/basic.css" rel="stylesheet" />
    <link href="~/Content/dropzone/dropzone.css" rel="stylesheet" />
    <style>
        .details-container td {
            vertical-align: middle !important;
        }

        .details-container th {
            vertical-align: middle !important;
        }

        .dz-details {
            display: none;
        }

        .dz-success-mark {
            display: none;
        }

        .dz-error-mark {
            display: none;
        }

        .dropzone {
            border: none;
        }

        .dz-error-message {
            display: none;
        }
    </style>
    <style>
        .details-container tr {
            height: 60px;
        }
        /*.course-name {
            width: 500px;
        }

        .course-description {
            width: 800px;
        }

        .ellipsis-text {
            white-space: nowrap;
            cursor: pointer;
            max-width: 100%;
            _width: 100%;
            overflow: hidden;
            text-overflow: ellipsis;
        }*/
        .short-text {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            width: 99%;
            /* height: 59px; */
            display: inline-block;
        }
    </style>
}
@section Scripts{
    @Scripts.Render("~/bundles/js/abhsTable")
    <script src="~/Content/ueditor/ueditor.config.js"></script>
    <script src="~/Content/ueditor/ueditor.all.js"></script>
    <script src="~/Content/ueditor/lang/zh-cn/zh-cn.js"></script>
    <script src="~/Scripts/dropzone/dropzone.js"></script>
    <script src="~/Scripts/PageScripts/coursemanage.details.js"></script>
}

AbhsChinese.Admin/Views/CourseManage/ListCourses.cshtml
@{
    ViewBag.PageTitle = "课程上下架";
}

<div class="ibox">
    <div class="ibox-content" style="padding:8px;">
        <div class="row">
            <div class="col-12">
                <button type="button" name="btn_state"
                        data-state="-1" class="btn btn-primary">
                    全部
                </button>
                <button type="button" name="btn_state"
                        data-state="2" class="btn btn-default">
                    待上架
                </button>
                <button type="button" name="btn_state"
                        data-state="3" class="btn btn-default">
                    已上架
                </button>
                <button type="button" name="btn_state"
                        data-state="4" class="btn btn-default">
                    已下架
                </button>
                <button type="button" name="btn_state"
                        data-state="1" class="btn btn-default">
                    未定价
                </button>
            </div>
        </div>
        <div class="row" style="margin-top:-8px;">
            <div class="col-12">
                <form role="form" class="form-inline search-form" id="form_search">
                    <input type="checkbox" checked class="search-hide" name="status" value="1" />
                    <input type="checkbox" checked class="search-hide" name="status" value="2" />
                    <input type="checkbox" checked class="search-hide" name="status" value="3" />
                    <input type="checkbox" checked class="search-hide" name="status" value="4" />
                    <div class="form-group">
                        <input type="text" name="id" placeholder="请输入编号" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="text" name="name" placeholder="请输入名称" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="text" name="ownerName" placeholder="请输入负责人" class="form-control">
                    </div>
                    <div class="form-group">
                        <select class="select2 normal" data-ajax--url="@Url.Action("GetCurriculumCategaries","Select2")"
                                data-ajax--cache="true"
                                data-placeholder="请选择类型" data-allow-clear="true"
                                name="courseType"></select>
                    </div>
                    <div class="form-group">
                        <select class="select2 normal" data-ajax--url="@Url.Action("GetGrades","Select2")"
                                data-ajax--cache="true"
                                data-placeholder="请选择年级" data-allow-clear="true"
                                name="grade"></select>
                    </div>
                    <button class="btn btn-white search" type="button">搜索</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12 table_container">
                <div id="table_list"></div>
                <div class="pagination"></div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    @Styles.Render("~/bundles/css/abhsTableStyles")
    <style>
        #form_search .search-hide {
            display: none;
        }

        ul {
            padding-inline-start: 0px;
            margin-bottom: 0px;
        }

        .img-info {
            width: 50px;
            height: 50px;
        }

        .short-text {
            word-wrap: break-word;
            word-break: normal;
            max-height: 40px;
            overflow: hidden;
            text-overflow: ellipsis;
            position:relative;
        }
            
    </style>
}

@section Scripts{
    @Scripts.Render("~/bundles/js/abhsTable")
    <script src="~/Scripts/common/abhs.common.js"></script>
    <script src="~/Scripts/common/select2.normal.init.js"></script>
    <script src="~/Scripts/PageScripts/coursemanage.list.js"></script>
}