AbhsChinese.Web/Models/LearningCenter/StudentCourseInfoViewModel.cs
using AbhsChinese.Domain.Dto.Response.Student;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AbhsChinese.Web.Models.LearningCenter
{
    public class StudentCourseInfoViewModel: DtoStudentCourseInfo
    {
        /// <summary>
        /// 已学过课程
        /// </summary>
        public List<DtoStudentLessonInfo> StudiedLesson { get; set; } = new List<DtoStudentLessonInfo>();
        /// <summary>
        /// 未学过课程
        /// </summary>
        public List<DtoStudentLessonInfo> NotStudyLesson { get; set; } = new List<DtoStudentLessonInfo>();
    }
}

AbhsChinese.Web/Models/StudentInfo/StuOwnVoucherSearch.cs
using AbhsChinese.Domain.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AbhsChinese.Web.Models.StudentInfo
{
    public class StuOwnVoucherSearch
    {
        public int PageIndex { get; set; }
        
        public StudentCashVoucherStatusEnum Status { get; set; }
    }
}

AbhsChinese.Web/Models/StudentInfo/StudentCashVoucherViewModel.cs
using AbhsChinese.Code.Common;
using AbhsChinese.Domain.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AbhsChinese.Web.Models.StudentInfo
{
    public class StudentCashVoucherViewModel
    {
        public int Ysv_Id { get; set; }

        public int Ysv_StudentId { get; set; }

        public int Ysv_CashVoucherId { get; set; }

        public string Ysv_VoucherNo { get; set; }

        public int Ysv_VoucherType { get; set; }

        public int Ycv_ExpireType { get; set; }

        public DateTime Ysv_ExpireDate { get; set; }

        public DateTime Ysv_TakenTime { get; set; }

        public string ExpireTime {
            get
            {
                if(Ycv_ExpireType==(int)ExpireTypeEnum.长期有效)
                {
                    return "长期有效";
                }
                return Ysv_TakenTime.ToString("yyyy-MM-dd") + " - " + Ysv_ExpireDate.ToString("yyyy-MM-dd");
            }
        }



        //现金券表
        public int Ycv_Id { get; set; }
        public string Ycv_Name { get; set; }
        public int Ycv_VoucherType { get; set; }
        public int Ycv_SchoolId { get; set; }
        public decimal Ycv_Amount { get; set; }
        public decimal Ycv_OrderAmountLimit { get; set; }
        public int Ycv_ApplyScopeType { get; set; }
        public int Ycv_ApplyGrade { get; set; }
        public int Ycv_CourseType { get; set; }
        public int Ycv_CourseId { get; set; }

        public string OrderAmountLimit
        {
            get
            {
                if (Ycv_OrderAmountLimit > 0)
                {
                    return "满￥" + Convert.ToInt32(Ycv_OrderAmountLimit) + "可用";
                }
                return "无限制";
            }
        }

        public string ApplyScoreType
        {
            get
            {
                if (Ycv_ApplyScopeType == (int)CashApplyScopeTypeEnum.全部课程)
                {
                    return "全部课程可用";
                }
                else if (Ycv_ApplyScopeType == (int)CashApplyScopeTypeEnum.指定类型)
                {
                    return "适用" + CustomEnumHelper.Parse(typeof(GradeEnum), Ycv_ApplyGrade) + "  " + CustomEnumHelper.Parse(typeof(CourseCategoryEnum), Ycv_CourseType);
                }
                else if (Ycv_ApplyScopeType == (int)CashApplyScopeTypeEnum.指定课程)
                {
                    return "适用" + Ycs_Name;
                }
                return "";
            }
        }

        public string ApplySchool
        {
            get
            {
                if (Ycv_SchoolId > 0)
                {
                    return "适用" + Bsl_SchoolName;
                }
                else
                {
                    return "适用全国校区";
                }
            }
        }

        public string VoucherCategory
        {
            get
            {
                if (Ycv_SchoolId > 0)
                {
                    return "校区券";
                }
                else
                {
                    return "全国券";
                }
            }
        }


        //校区表
        public string Bsl_SchoolName { get; set; }

        //课程表
        public string Ycs_Name { get; set; }

        public string ExpireDate { get; set; }
        public string TakenTime { get; set; }
        public string UsedTime { get; set; }
    }
}

AbhsChinese.Web/Models/StudentInfo/StudentInfoInputModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AbhsChinese.Web.Models.StudentInfo
{
    public class StudentInfoInputModel
    {
        public int StudentId { get; set; }

        public string HeadPhoto { get; set; }

        public string NickName { get; set; }

        public string Name { get; set; }

        public int Sex { get; set; }

        public DateTime Birthday { get; set; }

        public int Grade { get; set; }

        public string StudySchool { get; set; }

        public int Bst_Province { get; set; }

        public int Bst_City { get; set; }

        public int Bst_County { get; set; }

        public string Address { get; set; }
    }
}

AbhsChinese.Web/Models/StudentInfo/StudentInfoViewModel.cs
using AbhsChinese.Code.Common;
using AbhsChinese.Domain.Enum;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;

namespace AbhsChinese.Web.Models.StudentInfo
{
    public class StudentInfoViewModel
    {
        public int Bst_Id { get; set; }
        /// <summary>
        /// 学号
        /// </summary>
        public string Bst_No { get; set; }

        /// <summary>
        /// 姓名
        /// </summary>
        public string Bst_Name { get; set; }

        /// <summary>
        /// 昵称
        /// </summary>
        public string Bst_NickName { get; set; }

        /// <summary>
        /// 称号
        /// </summary>
        public string Salutation => SalutationEnum.书童.ToString();

        /// <summary>
        /// 头像
        /// </summary>
        public string Bst_Avatar { get; set; }

        /// <summary>
        /// 性别
        /// </summary>
        public int Bst_Sex { get; set; }

        /// <summary>
        /// 生日
        /// </summary>
        public DateTime Bst_Birthday { get; set; }

        /// <summary>
        /// 年级
        /// </summary>
        public int Bst_Grade { get; set; }

        /// <summary>
        /// 手机号
        /// </summary>
        public string Bst_Phone { get; set; }

        /// <summary>
        /// 校区
        /// </summary>
        public int Bst_SchoolId { get; set; }
        
        /// <summary>
        /// 在读学校
        /// </summary>
        public string Bst_StudySchool { get; set; }

        /// <summary>
        /// 省
        /// </summary>
        public int Bst_Province { get; set; }

        /// <summary>
        /// 市
        /// </summary>
        public int Bst_City { get; set; }

        /// <summary>
        /// 区
        /// </summary>
        public int Bst_County { get; set; }

        /// <summary>
        /// 收货地址
        /// </summary>
        public string Bst_Address { get; set; }

        public string SchoolName { get; set; }

        public string Avatar => string.IsNullOrEmpty(Bst_Avatar)?"":Bst_Avatar.ToOssPath();
        public string Sex => CustomEnumHelper.Parse(typeof(SexEnum), Bst_Sex);
        public string Birthday => Bst_Birthday.ToString("yyyy年MM月dd日");
        public string BirthdayEdit => Bst_Birthday.CompareTo(Convert.ToDateTime("1900-01-01")) == 0 ? DateTime.Now.ToString("yyyy-MM-dd") : Bst_Birthday.ToString("yyyy-MM-dd");
        public string Grade => CustomEnumHelper.Parse(typeof(GradeEnum), Bst_Grade);

        public int ApplyStatus { get; set; }

        public string ApplySchoolName { get; set; }
    }
}

AbhsChinese.Web/Controllers/LearningCenterController.cs
using AbhsChinese.Bll;
using AbhsChinese.Code.Common;
using AbhsChinese.Domain.Dto.Request;
using AbhsChinese.Domain.Dto.Request.Student;
using AbhsChinese.Domain.Dto.Response;
using AbhsChinese.Domain.Dto.Response.Student;
using AbhsChinese.Domain.Enum;
using AbhsChinese.Domain.JsonEntity.Answer;
using AbhsChinese.Domain.JsonEntity.Coin;
using AbhsChinese.Domain.JsonTranslator;
using AbhsChinese.Web.Models.CurriculumSetViewModel;
using AbhsChinese.Web.Models.LearningCenter;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using static AbhsChinese.Domain.JsonEntity.Answer.StuBlankAnswer;

namespace AbhsChinese.Web.Controllers
{
    /// <summary>
    /// 学习中心控制器
    /// </summary>
    public class LearningCenterController : BaseController
    {
        // GET: LearningCenter
        public ActionResult Index()
        {
            SumStudentBll sumStudentBll = new SumStudentBll();
            DtoSumStudent student = sumStudentBll.GetSumByStuDate(GetCurrentUser().StudentId);
            student.Name = GetCurrentUser().Name;
            student.Sex = GetCurrentUser().Sex;
            if (!string.IsNullOrEmpty(WebHelper.GetCookie("CashVoucher")))
            {
                student.ShowTicket = true;
                WebHelper.RemoveCookie("CashVoucher");
            }

            return View(student);
        }

        public ActionResult CoruseInfo(int id)
        {
            StudentStudyBll bll = new StudentStudyBll();
            int studentid = GetCurrentUser().StudentId;
            StudentCourseInfoViewModel info = bll.GetCourseProgress(studentid, id).ConvertTo<StudentCourseInfoViewModel>();
            info.TeacherImg = ConfigurationManager.AppSettings["OssHostUrl"] + info.TeacherImg;
            var list = bll.GetLessonProgressByStudent(studentid, id);
            info.StudiedLesson = list.Where(s => s.IsStudyOver).ToList();
            info.NotStudyLesson = list.Where(s => !s.IsStudyOver).ToList();
            return View(info);
        }

        /// <summary>
        /// 课时学习视图
        /// </summary>
        /// <returns></returns>
        public ActionResult LessonStudy(int courseId, int lessonId)
        {
            StudentStudyBll bll = new StudentStudyBll();
            var p = bll.GetLastProgressByStudent(GetCurrentUser().StudentId, courseId, lessonId);
            if (p != null)
            {
                var lesson = new LessonBll().GetLesson(lessonId);//获取课程数据信息
                Chapter chapter = new Chapter()
                {
                    isApprove = false,
                    lastTimeIsOver = p.Yle_IsFinished || p.Yle_UnitIndex == 1,//如果已经完成或者从第一页开始,我们认为上次学习已经结束了
                    courseId = p.Yle_CourseId,
                    lessonId = p.Yle_LessonId,
                    lessonIndex = lesson.Ycl_Index,
                    lessonProgressId = p.Yle_Id,
                    progressKey = p.Yle_key,
                    startAddGoldsPageNum = p.Yle_CoinFromUIndex,
                    startPageNum = p.Yle_UnitIndex,
                    totalPageNum = lesson.Ycl_UnitCount
                };
                return View(chapter);
            }
            else
            {
                throw new Exception("课时数据错误");
            }
        }
        /// <summary>
        /// 审批界面
        /// </summary>
        /// <param name="ApproveKey"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult LessonApprove(string ApproveKey)
        {
            var jm = Encrypt.DecryptQueryString(ApproveKey).Split('_');//解密数据
            int courseId, lessonId, unitId, r;//定义课程id,课时id,单元id,随机数
            if (jm.Length == 4 && int.TryParse(jm[0], out r) && int.TryParse(jm[1], out unitId) && int.TryParse(jm[2], out lessonId) && int.TryParse(jm[3], out courseId))
            {
                Chapter chapter = new Chapter()
                {
                    isApprove = true,
                    lastTimeIsOver = courseId == 0,
                    startPageNum = unitId,
                    progressKey = Encrypt.MD5Hash(unitId.ToString(), "jzxd")
                };
                return View(chapter);
            }
            else
            {
                throw new Exception("课时数据错误");
            }
        }

        /// <summary>
        /// 获取用户的课程完成与未完成数量
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetCourserCount()
        {
            StudentStudyBll bll = new StudentStudyBll();
            var data = bll.GetCourseCountByStudent(GetCurrentUser().StudentId);
            return Json(new JsonResponse<object>
            {
                State = true,
                ErrorCode = 0,
                ErrorMsg = "",
                Data = new { totel = data.Item1, notFinish = data.Item2, finished = data.Item3 }
            });

        }

        /// <summary>
        /// 根据课程完成状态分页查询学生课程信息
        /// </summary>
        /// <param name="search"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetCourseByPage(DtoStudentCourseSearch search)
        {
            search.StudentId = GetCurrentUser().StudentId;
            StudentStudyBll bll = new StudentStudyBll();
            var list = bll.GetCourseProgressByStudentSearch(search);
            list.ForEach(s =>
            {
                s.TeacherImg = ConfigurationManager.AppSettings["OssHostUrl"] + s.TeacherImg;
            });
            return Json(new JsonResponse<object>
            {
                State = true,
                ErrorCode = 0,
                ErrorMsg = "",
                Data = new { totel = search.Pagination.TotalCount, list = list }
            });
        }

        /// <summary>
        /// 根据课程id获取学生课时信息
        /// </summary>
        /// <param name="courseId"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetLessons(int courseId)
        {
            StudentStudyBll bll = new StudentStudyBll();
            var list = bll.GetLessonProgressByStudent(GetCurrentUser().StudentId, courseId);
            return Json(new JsonResponse<List<DtoStudentLessonInfo>>
            {
                State = true,
                ErrorCode = 0,
                ErrorMsg = "",
                Data = list
            });
        }
        /// <summary>
        /// 根据课程id,课时id获取连续几页数据
        /// </summary>
        /// <param name="courseid">课程id</param>
        /// <param name="lessonid">课时id</param>
        /// <param name="page">开始页</param>
        /// <param name="pagesize">请求页数</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetLessonPage(DtoLessonUnitSearch search, bool isApprove = false)
        {
            LessonUnitBll bll = new LessonUnitBll();
            search.StudentID = GetCurrentUser().StudentId;//设置当前学生id
            if (isApprove) { search.Pagination.PageSize = 1; }//如果是审批的情况,只返回一条数据
            var pages = bll.SelectUnitByNext(search);
            List<int> mediaIDs = new List<int>();
            List<int> textIDs = new List<int>();
            var list = pages.Select(p => new Page()
            {
                pageId = p.Id,
                pageNum = p.Index,
                pageName = p.Name,
                coinsKey = Encrypt.EncryptQueryString($"{p.Coins}_{p.Id}_{p.LessonId}_{p.CourseId}"),//金币加密串(加密内容为"单元金币数_单元id_课时id_课程id")//Remark1
                steps = p.Steps.Select(s => new Step()
                {
                    stepNum = s.StepNum,
                    actions = s.Actions.Select(a => ActionTranslator.DataToViewData(a, mediaIDs, textIDs)).ToList()
                }).ToList()
            }).ToList();
            //如果媒体id或文本id有值的话
            if (mediaIDs.Count > 0 || textIDs.Count > 0)
            {
                ResourceBll rbll = new ResourceBll();
                var medias = rbll.GetMediaObjectByIdList(mediaIDs.Distinct().ToList(), true);//获取所有的媒体对象字典
                var texts = rbll.GetTextObjectByIdList(textIDs.Distinct().ToList());//获取文本对象字典

                list.ForEach(p =>
                {
                    p.steps.ForEach(s =>
                    {
                        s.actions.ForEach(a =>
                        {
                            ActionTranslator.SetViewDataMedia(a, medias, texts);
                        });
                    });
                });
            }

            return Json(new JsonResponse<List<Page>>
            {
                State = true,
                ErrorCode = 0,
                ErrorMsg = "",
                Data = list
            });
        }

        /// <summary>
        /// 服务端审批调取单页数据接口
        /// </summary>
        /// <param name="unitid">单元id</param>
        /// <param name="isshow">是否是制作中的展示(及是否从radis中取数据)</param>
        /// <param name="jy">校验值</param>
        /// <returns></returns>
        [HttpPost]
        [AllowAnonymous]
        public JsonResult GetUnitPage(int unitid, bool isshow, string jy)
        {
            if (Encrypt.MD5Hash(unitid.ToString(), "jzxd") == jy)
            {
                DtoLessonUnit p = null;
                LessonUnitBll bll = new LessonUnitBll();
                if (!isshow)
                {
                    p = bll.SelectUnit(unitid, 0);
                }
                else
                {
                    p = bll.GetUnitFromRadis(unitid);
                }
                List<int> mediaIDs = new List<int>();
                List<int> textIDs = new List<int>();
                var page = new Page()
                {
                    pageId = p.Id,
                    pageNum = p.Index,
                    pageName = p.Name,
                    coinsKey = Encrypt.EncryptQueryString($"{p.Coins}_{p.Id}_{p.LessonId}_{p.CourseId}"),//金币加密串(加密内容为"单元金币数_单元id_课时id_课程id")//Remark1

AbhsChinese.Web/Views/LearningCenter/CoruseInfo.cshtml
@{
    ViewBag.Title = "开始练习";
    bool showStudied = Model.NotStudyLesson.Count == 0 && Model.StudiedLesson.Count > 0;//用于存储是否直接展示已学习的内容
}

@model AbhsChinese.Web.Models.LearningCenter.StudentCourseInfoViewModel
@section Styles{
    <style>
        html, body {
            height: 100%;
        }

        #practicetab .tablist {
            cursor: pointer;
        }
    </style>
}
<div class="bodycontent">
    @Html.Partial("_NavBar")
    <div class="navigation">
        <div class="navigationl fl">
            <span class="arrow-right"></span>
            <a href="@Url.Action("Index","LearningCenter")">学习中心</a><em><img src="/Images/StudentInfo/back.png" /></em><a href="#">课程学习</a>
        </div>
        <!-- <div class="navigationr"><a href="#">< &nbsp;返回</a></div> -->
    </div>
    <div class="maincontent">
        <div class="mainbjtop"><img src="/Images/StudentInfo/orderbodytop.png" /></div>
        <div class="maincenter startpracticepage">
            <div class="ptitle">
                <div class="fl"><span class="label">@Model.CourseTypeStr</span><em>@Model.CourseName（共 @Model.LessonsNum 课时）</em></div>
                <div class="info"><span>@Model.LessonsFinishedNum</span>/@Model.LessonsNum</div>
            </div>
            <div class="infotext"><span>适用年级：@Model.GradeStr</span><span>教材版本：部编版</span><span>校区班级：@Model.ClassName</span></div>
            <div class="phimg">
                @if (Model.TeacherID != 0)
                {
                    <img src="@Model.TeacherImg" /><span>@(Model.TeacherName)</span> <em>班主任</em>
                }
            </div>

            <div class="tabbx">
                <div class="tab" id="practicetab">
                    <div class="tablist @(!showStudied?"active":"") fl">待学习（@Model.NotStudyLesson.Count 课时）</div>
                    <div class="tablist @(showStudied?"active":"") fl">已学习（@Model.StudiedLesson.Count 课时）</div>
                </div>
            </div>
            <div class="tabcontbox">
                @if (Model.NotStudyLesson.Count > 0)
                {
                    <ul style="display:@(showStudied?"none":"block");">
                        @for (int i = 0; i < Model.NotStudyLesson.Count; i++)
                        {
                            if (Model.NotStudyLesson[i].LessonIndex <= Model.NextLessonNum)
                            {
                        <li class="active">
                            <div class="titl fl">【 第 @Model.NotStudyLesson[i].LessonIndex.ToString().PadLeft(2, '0') 课时 】@Model.NotStudyLesson[i].LessonName</div>
                            <div class="operate"><a href="/LearningCenter/LessonStudy?courseId=@Model.CourseID&lessonId=@Model.NotStudyLesson[i].LessonId">开始学习</a></div>
                        </li>
                            }
                            else
                            {
                        <li>
                            <div class="titl fl">【 第 @Model.NotStudyLesson[i].LessonIndex.ToString().PadLeft(2, '0') 课时 】@Model.NotStudyLesson[i].LessonName</div>
                            <div class="operate"></div>
                        </li>

                            }
                        }
                    </ul>
                }
                else
                {
                    <div class="pageimgerror" style="display:@(showStudied?"none":"block");">
                        <img class="error-img" src="/Images/StudentInfo/nop.png" />
                    </div>
                }
                @if (Model.StudiedLesson.Count > 0)
                {
                    <ul style="display:@(showStudied?"block":"none");">
                        @for (int i = 0; i < Model.StudiedLesson.Count; i++)
                        {
                        <li class="active">
                            <div class="titl fl">【 第 @Model.StudiedLesson[i].LessonIndex.ToString().PadLeft(2, '0') 课时 】@Model.StudiedLesson[i].LessonName</div>
                            <div class="operate"><a href="/LearningCenter/LessonStudy?courseId=@Model.CourseID&lessonId=@Model.StudiedLesson[i].LessonId">开始学习</a></div>
                        </li>
                        }
                    </ul>
                }
                else
                {
                    <div class="pageimgerror" style="display:@(showStudied?"block":"none");">
                        <img class="error-img" src="/Images/StudentInfo/nop.png" />
                    </div>
                }
            </div>
        </div>
        <div class="mainbjbottom"><img src="/Images/StudentInfo/orderbodybottom.png" /></div>
    </div>

</div>
<div class="bodybjleft">
    <img src="/Images/StudentInfo/homeLeft.png" />
</div>
<div class="bodybjright">
    <img src="/Images/StudentInfo/homeRight.png" />
</div>
@section Scripts{
    <script>
        $(function () {
            $('#practicetab .tablist').click(function () {
                $(this).addClass('active').siblings().removeClass('active');
                $('.tabcontbox').children().eq($(this).index()).show().siblings().hide();
            })
            function geth() {
                var H = $(window).height() - $('.navigation').height() - 20 - ($('.mainbjtop').height() * 2) - 270;
                $('.startpracticepage').css({
                    'min-height': H
                })
            }
            geth();
            $(window).resize(function () {
                geth()
            });

        })
    </script>
}

AbhsChinese.Web/Views/LearningCenter/_StudentInfo.cshtml
@using AbhsChinese.Domain.Dto.Response.Student
@using AbhsChinese.Domain.Enum
@model DtoSumStudent

<div class="bjboxbox">
    <div class="bjboxboxtop"><img src="/Images/StudentInfo/tbjtop.png" /></div>
    <div class="bjboxboxcenter" style="height: 250px;">
        <div class="infoperson">
            <div class="photoimg">
                @{
                    if (string.IsNullOrEmpty(Model.Avatar))
                    {
                        if (Model.Sex == (int)SexEnum.男)
                        {
                            <img src="/Images/StudentInfo/u396.png" />
                        }
                        else
                        {
                            <img src="/Images/StudentInfo/portrait.png" />
                        }
                    }
                    else
                    {
                        <img src="@Model.AvatarStr" />
                    }
                }
                <div class="usname">@Model.Salutation</div>
            </div>
            <div class="userinfo">
                <!-- <img src="/Images/StudentInfo/man.png" /> -->
                <img src="@(Model.Sex==(int)SexEnum.男?"/Images/StudentInfo/man.png":"/Images/StudentInfo/woman.png")" />&nbsp;&nbsp;@Model.Name
            </div>
            <div class="userinfo1">
                @(string.IsNullOrEmpty(Model.School)?"未绑定校区":Model.School)
            </div>
            <div class="userinfo2">
                <div class="usitem">
                    <div class="text">今日学习</div>
                    <div class="text1"><span>@Model.StudyMinutes</span>分钟</div>
                </div>
                <div class="usitem">
                    <div class="text">学习天数</div>
                    <div class="text1"><span class="label1">@Model.StudyDayCount</span>天</div>
                </div>
                <div class="usitem">
                    <div class="text">金币数量</div>
                    <div class="text1"><span class="label2">@Model.Coins</span>个</div>
                </div>
            </div>
        </div>

    </div>
    <div class="bjboxboxtop"><img src="/Images/StudentInfo/tbjbottom.png" /></div>
</div>